total_private_domains: unlimited
total_reserved_route_ports: "0"
total_service_keys: unlimited
app_instance_limit: unlimited
app_task_limit: unlimited
memory-limit: 10G
instance-memory-limit: unlimited
total-routes: "1000"
total-services: "100"
paid-service-plans-allowed: true
