---
opsman_credentials: &opsman_credentials
  SKIP_SSL_VALIDATION: true
  OPSMAN_URL: ((opsman_uri))
  OPSMAN_USERNAME: ((opsman.username))
  OPSMAN_PASSWORD: ((opsman.password))

s3_credentials: &s3_credentials
  access_key_id: ((s3_access_key_id))
  bucket: ((s3_pivnet_products_bucket))
  region_name: ((s3_region_name))
  secret_access_key: ((s3_secret_access_key))

jobs:
- name: export-om-installation
  serial: true
  plan:
  - aggregate:
    - get: daily-trigger
      trigger: true
    - get: bbr-pipeline-tasks-repo
  - task: export-om-installation
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation/task.yml
    tags: ["sandbox-worker"]
    params:
      SKIP_SSL_VALIDATION: true
      OPSMAN_URL: ((opsman_uri))
      OPSMAN_USERNAME: ((opsman.username))
      OPSMAN_PASSWORD: ((opsman.password))
  - put: om-backup-artifact
    params:
      file: om-installation/installation.zip

- name: bbr-backup-pas
  serial: true
  plan:
  - aggregate:
    - get: daily-trigger
      trigger: true
      passed: [export-om-installation]
    - get: bbr-pipeline-tasks-repo
    - get: bbr-release
  - task: check-opsman-status
    file: bbr-pipeline-tasks-repo/tasks/check-opsman-status/task.yml
    tags: ["sandbox-worker"]
    params:
      <<: *opsman_credentials
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags: ["sandbox-worker"]
  - task: bbr-backup-pas
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pas/task.yml
    tags: ["sandbox-worker"]
    params:
      <<: *opsman_credentials
    on_failure:
      task: bbr-cleanup-pas
      file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pas/task.yml
      tags: ["sandbox-worker"]
      params:
        <<: *opsman_credentials
  - put: pas-backup-bucket
    params:
      file: pas-backup-artifact/pas-backup.tar

- name: bbr-backup-pks
  serial: true
  plan:
  - aggregate:
    - get: daily-trigger
      trigger: true
      passed: [bbr-backup-pas]
    - get: bbr-pipeline-tasks-repo
    - get: bbr-release
  - task: check-opsman-status
    file: bbr-pipeline-tasks-repo/tasks/check-opsman-status/task.yml
    tags: ["sandbox-worker"]
    params:
      <<: *opsman_credentials
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags: ["sandbox-worker"]
  - task: bbr-backup-pks
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-pks/task.yml
    tags: ["sandbox-worker"]
    params:
      <<: *opsman_credentials
    on_failure:
      task: bbr-cleanup-pks
      file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-pks/task.yml
      tags: ["sandbox-worker"]
      params:
        <<: *opsman_credentials
  - put: pks-backup-bucket
    params:
      file: pks-backup-artifact/pks-backup.tar

- name: bbr-backup-director
  serial: true
  plan:
  - aggregate:
    - get: daily-trigger
      trigger: true
      passed: [bbr-backup-pks]
    - get: bbr-pipeline-tasks-repo
    - get: bbr-release
  - task: check-opsman-status
    file: bbr-pipeline-tasks-repo/tasks/check-opsman-status/task.yml
    tags: ["sandbox-worker"]
    params:
      <<: *opsman_credentials
  - task: extract-binary
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
    tags: ["sandbox-worker"]
  - task: bbr-backup-director
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director/task.yml
    tags: ["sandbox-worker"]
    params:
      <<: *opsman_credentials
    on_failure:
      task: bbr-cleanup-director
      file: bbr-pipeline-tasks-repo/tasks/bbr-cleanup-director/task.yml
      params:
        <<: *opsman_credentials
  - put: director-backup-bucket
    params:
      file: director-backup-artifact/director-backup.tar

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: daily-trigger
  type: time
  source:
    interval: 24h
- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks.git
    branch: master
- name: om-backup-artifact
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: installation/installation.zip
- name: pas-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: backup/pas-backup.tar
- name: pks-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: backup/pks-backup.tar
- name: director-backup-bucket
  type: s3
  source:
    <<: *s3_credentials
    versioned_file: backup/director-backup.tar
- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: p-bosh-backup-and-restore