org: isolated
org-billingmanager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
org-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
org-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
private-domains:
- iso.miclip.io
enable-remove-private-domains: true
shared-private-domains: []
enable-remove-shared-private-domains: true
enable-org-quota: false
enable-remove-users: true
default_isolation_segment: iso_test
service-access: {}
named_quota: ""
