product-name: p-isolation-segment
product-properties:
  .isolated_diego_cell.placement_tag:
    value: ((placement_tag))
  .isolated_router.disable_insecure_cookies:
    value: false
  .isolated_router.drain_wait:
    value: 20
  .isolated_router.enable_write_access_logs:
    value: true
  .isolated_router.enable_zipkin:
    value: true
  .isolated_router.lb_healthy_threshold:
    value: 20
  .isolated_router.request_timeout_in_seconds:
    value: 900
  .properties.container_networking:
    selected_option: enable
    value: enable
  .properties.enable_garden_containerd_mode:
    value: true
  .properties.enable_silk_policy_enforcement:
    value: true
  .properties.enable_smb_volume_driver:
    value: false
  .properties.garden_disk_cleanup:
    selected_option: reserved
    value: reserved
  .properties.garden_disk_cleanup.reserved.reserved_space_for_other_jobs_in_mb:
    value: 15360
  .properties.gorouter_ssl_ciphers:
    value: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  .properties.haproxy_client_cert_validation:
    selected_option: none
    value: none
  .properties.haproxy_forward_tls:
    selected_option: disable
    value: disable
  .properties.haproxy_hsts_support:
    selected_option: disable
    value: disable
  .properties.haproxy_max_buffer_size:
    value: 16384
  .properties.haproxy_ssl_ciphers:
    value: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: ((ssl_cert.certificate))
        private_key_pem: ((ssl_cert.private_key))
      name: '*.iso.sandbox.miclip.io'
  .properties.networking_point_of_entry:
    selected_option: terminate_at_router
    value: terminate_at_router
  .properties.nfs_volume_driver:
    selected_option: disable
    value: disable
  .properties.route_integrity:
    selected_option: tls_verify
    value: tls_verify
  .properties.route_services_internal_lookup:
    value: false
  .properties.router_backend_max_conn:
    value: 500
  .properties.router_client_cert_validation:
    selected_option: request
    value: request
  .properties.router_enable_proxy:
    value: false
  .properties.router_keepalive_connections:
    selected_option: enable
    value: enable
  .properties.router_prune_all_stale_routes:
    value: false
  .properties.routing_disable_http:
    value: false
  .properties.routing_log_client_ips:
    selected_option: log_client_ips
    value: log_client_ips
  .properties.routing_minimum_tls_version:
    selected_option: tls_v1_2
    value: tls_v1_2
  .properties.routing_table_sharding_mode:
    selected_option: isolation_segment_only
    value: isolation_segment_only
  .properties.routing_tls_termination:
    selected_option: router
    value: router
  .properties.skip_cert_verify:
    value: false
  .properties.system_logging:
    selected_option: disabled
    value: disabled
  .properties.system_metrics_enabled:
    value: true
network-properties:
  network:
    name: iso
  other_availability_zones:
  - name: zone-1
  - name: zone-2
  - name: zone-3
  singleton_availability_zone:
    name: zone-1
resource-config:
  isolated_diego_cell:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: false
  isolated_ha_proxy:
    instances: 0
    instance_type:
      id: automatic
    internet_connected: false
  isolated_router:
    instances: 1
    instance_type:
      id: automatic
    internet_connected: false
    elb_names:
    - sandbox-iso-lb
    additional_vm_extensions:
    - iso-lb-security-group